language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
on:
  branch: production
deploy:
  provider: surge
  project: ./dist/
  skip_cleanup: true
  on: production